scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'demo'
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus'
#    basic_auth:
#      username: admin
#      password: admin
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['172.17.0.1:8080']
